server:
  port: 8080

spring:
  application:
    name: holidaykeeper-backend

  datasource:
    url: jdbc:h2:mem:holidaydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update # develop mode: update, deploy: validate or none
    show-sql: false # SQL log print mode
    properties:
      hibernate:
        format_sql: true # formatting sql
        jdbc:
          batch_size: 30


  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

nager:
  api:
    base-url: https://date.nager.at/api/v3
    connect-timeout: 5000
    read-timeout: 10000